### ISSUE TITLE
License missing?

### ISSUE THREAD

**Issue by taruti** [vdobler/chart#15]
Hello

The chart package looks very interesting, but it seems to lack a license?

**Comment by hnakamur** [comment]
Hi @vdobler
Thank you for creating and sharing a nice library!

Could you add LICENSE file?
The following page might help for choosing license.

"Choosing an OSS license doesn’t need to be scary - ChooseALicense.com"
http://choosealicense.com/

Thanks.

**Comment by vdobler** [comment]
Done.
