### ISSUE TITLE
Problems with text overflow in Key/Legend for svg files

### ISSUE THREAD

**Issue by fedemengo** [vdobler/chart#32]
I copied the dumper for both png/svg. When I plot the result, the text in the legend of the svg file overflow its box

png looks good

![entropy-1680123884](https://user-images.githubusercontent.com/19249682/228669280-85b4b942-42fe-43ff-b2f3-197eb5c907e7.png)

svg overflows

![entropy-1680123884](https://user-images.githubusercontent.com/19249682/228669287-7e456e02-e543-43fc-96c2-c2cad6e8e804.svg)

The code I'm using for plotting is [here](https://github.com/fedemengo/d2bist/blob/28f92bf6b5a186a4785c21abf4463ff24073459e/pkg/types/types.go#L183) and the minimal config for the key is [here](https://github.com/fedemengo/d2bist/blob/28f92bf6b5a186a4785c21abf4463ff24073459e/pkg/types/types.go#L226)

Awesome work! I really like these charts

**Comment by vdobler** [comment]
I'm not really sure I understand the problem as both outputs basically look the same to me.
Can you highlight the problem?

**Comment by fedemengo** [comment]
might be nitpicking, but this is what I mean

<img width="170" alt="Screenshot 2023-04-05 at 22 15 19" src="https://user-images.githubusercontent.com/19249682/230199595-524ada3f-7060-42d5-b0a3-86017666f7fc.png">

**Comment by fedemengo** [comment]
also, it only happens in firefox. Closing since in chrome looks fine! Sorry for the noise
